parameters:

  header:
    ## Header information is used for logging. It is good practice to give your simulations explicit names
    title: Poroelastic simulation (P-SV Waves) # name for your simulation
    # A detailed description for your simulation
    description: |
      Material systems : Poroelastic domain (1)
      Interfaces : None
      Sources : Force source (1)
      Boundary conditions : Neumann BCs on all edges
      Debugging comment : This test tests elastic compute_forces routine

  simulation-setup:
    elastic-wave: "P_SV"
    ## quadrature setup
    quadrature:
      quadrature-type: GLL4

    ## Solver setup
    solver:
      time-marching:
        type-of-simulation: forward
        time-scheme:
          type: Newmark
          dt: 1.0e-4
          nstep: 1000

    simulation-mode:
      forward:
        writer:
          seismogram:
            format: ascii
            directory: "OUTPUT_FILES/results"

  receivers:
    stations: "OUTPUT_FILES/STATIONS"
    angle: 0.0
    seismogram-type:
      - displacement
    nstep_between_samples: 1

  ## Runtime setup
  run-setup:
    number-of-processors: 1
    number-of-runs: 1

  ## databases
  databases:
    mesh-database: "OUTPUT_FILES/database.bin"

  sources: "source.yaml"
