#pragma once

#include "specfem/enums.hpp"
#include "specfem/macros/tag_dispatch.hpp"
#include "specfem/medium_container.hpp"
#include "specfem/mesh/attenuation_config.hpp"
#include "specfem/tag_dispatch/storage.hpp"
#include "specfem/tags.hpp"
#include "specfem/units.hpp"
#include "specfem/utilities/logarithmic_center.hpp"
#include <Kokkos_Core.hpp>
#include <optional>
#include <vector>

namespace specfem::mesh {

template <specfem::element::dimension_tag Dimension> struct materials;

/**
 * @brief 3D specialization for MESHFEM3D material database management
 *
 * This specialized implementation manages material properties for 3D
 * spectral element simulations generated by MESHFEM3D. It provides:
 *
 * - Storage for materials read from MESHFEM3D database files
 * - Type-safe material containers organized by medium and property types
 * - Mapping between spectral elements and their material specifications
 * - Template metaprogramming for compile-time material type dispatch
 *
 * This ensures comprehensive material support while maintaining type safety
 * and enabling compile-time optimizations in the spectral element framework.
 *
 * @see specfem::medium_container::material
 *
 * @code
 * // Create materials database for 1000 elements with 5 unique materials
 * spectral::mesh::meshfem3d::materials<specfem::element::dimension_tag::dim3>
 *     materials(1000, 5);
 *
 * // Add an isotropic elastic material from MESHFEM3D database
 * specfem::medium_container::material<specfem::element::medium_tag::elastic,
 *                          specfem::element::property_tag::isotropic>
 * elastic_mat; materials.add_material(elastic_mat, database_index);
 *
 * // Retrieve material for element during simulation
 * auto material = materials.get_material<specfem::element::medium_tag::elastic,
 *                                       specfem::element::property_tag::isotropic>(elem_id);
 * @endcode
 */
template <> struct materials<specfem::element::dimension_tag::dim3> {
  /**
   * @brief Dimension tag for compile-time type identification
   *
   * Fixed to dim3 for this specialization, used for template metaprogramming
   * and ensuring compatibility with the SPECFEM++ dimension system.
   */
  static constexpr auto dimension_tag = specfem::element::dimension_tag::dim3;

  /**
   * @brief Material specification linking elements to material database entries
   *
   * Associates spectral elements with their corresponding material types and
   * database indices from MESHFEM3D material files. This structure provides
   * the mapping between mesh topology and material properties.
   *
   * Used internally to maintain the association between:
   * - Element indices in the mesh
   * - Material types (medium + property combinations)
   * - Original database indices from MESHFEM3D input files
   * - Local indices within type-specific material containers
   */
  struct material_specification {
    /** @brief Physical medium type (acoustic, elastic, etc.) */
    specfem::element::medium_tag type;

    /** @brief Material property type (isotropic, anisotropic) */
    specfem::element::property_tag property;

    /** @brief Attenuation type (none, constant_isotropic, etc.) */
    specfem::element::attenuation_tag attenuation;

    /** @brief Local index within the type-specific material container */
    int index;

    /** @brief Original database index from MESHFEM3D material files */
    int database_index;

    /** @brief Default constructor initializing with default values */
    material_specification() = default;

    /**
     * @brief Construct material specification from components
     *
     * @param type Physical medium type for wave equation selection
     * @param property Material property type for constitutive relations
     * @param index Local material index within container
     * @param database_index Original MESHFEM3D database index
     */
    material_specification(specfem::element::medium_tag type,
                           specfem::element::property_tag property,
                           specfem::element::attenuation_tag attenuation,
                           int index, int database_index)
        : type(type), property(property), attenuation(attenuation),
          index(index), database_index(database_index) {};
  };

  /**
   * @brief Template container for materials of specific type and property
   *
   * Stores material objects of a specific medium/property combination with
   * count tracking for efficient memory management. Each container holds
   * materials of exactly one type (e.g., all elastic isotropic materials).
   *
   * This design enables:
   * - Type-safe material storage and retrieval
   * - Efficient memory layout for materials of the same type
   * - Compile-time optimization based on material properties
   * - Integration with SPECFEM++ template metaprogramming system
   *
   * @tparam type Medium type (acoustic, elastic)
   * @tparam property Property type (isotropic, anisotropic)
   */
  template <specfem::element::medium_tag type,
            specfem::element::property_tag property,
            specfem::element::attenuation_tag attenuation>
  struct material {
    /** @brief Number of materials stored in this container */
    int n_materials = 0;

    /** @brief Storage for material objects of this type/property combination */
    std::vector<

        specfem::medium_container::material<dimension_tag, type, property,
                                            attenuation> >
        element_materials;

    /** @brief Default constructor creating empty container */
    material() : n_materials(0) {}

    /**
     * @brief Construct container from existing material vector
     *
     * @param n_materials Number of materials to store
     * @param l_material Vector of materials to initialize container with
     */
    material(const int n_materials,
             const std::vector<specfem::medium_container::material<
                 dimension_tag, type, property, attenuation> > &l_material);
  };

  /** @name Core Data Members */
  /** @{ */

  /** @brief Total number of materials across all type containers */
  int n_materials = 0;

  int nspec; ///< Total number of spectral elements in the mesh

  /**
   * @brief Mapping from element index to material specification
   *
   * For each spectral element in the mesh, stores the material specification
   * that identifies which material container and index to use for retrieving
   * the element's material properties. This provides the link between mesh
   * topology and material database entries.
   */
  std::vector<material_specification> material_index_mapping;

private:
  /** @} */

  /** @name Auto-Generated Material Containers */
  /** @{ */

  static constexpr auto combinations =
      specfem::tag_dispatch::dimension_set<dimension_tag>{} *
      MEDIUM_SET(acoustic, elastic) * PROPERTY_SET(isotropic) *
      ATTENUATION_SET(none, constant_isotropic);
  template <typename TagsType>
  using MaterialContainerTemplate =
      material<TagsType::medium_tag, TagsType::property_tag,
               TagsType::attenuation_tag>;

  specfem::tag_dispatch::TypedStorage<MaterialContainerTemplate,
                                      decltype(combinations)>
      material_containers;

  /** @} */
public:
  /** @name Constructors */
  /** @{ */

  /**
   * @brief Default constructor creating empty materials database
   *
   * Creates an uninitialized materials collection with no elements or
   * materials. Suitable for delayed initialization or when material
   * data will be populated later through other means.
   */
  materials() : n_materials(0), nspec(0) {}

  /** @} */

  /** @name Material Access Interface */
  /** @{ */

  /**
   * @brief Retrieve material object for a specific element with type safety
   *
   * Returns the material object associated with the given element index using
   * compile-time template parameters for the specified medium and property
   * types.
   *
   * @tparam MediumTag Medium type (acoustic, elastic)
   * @tparam PropertyTag Property type (isotropic, anisotropic)
   * @param index Element index to retrieve material for
   * @return Material object with specified medium and property types
   *
   * @code
   * // Retrieve elastic isotropic material for element 42
   * auto elastic_material = materials.get_material<
   *     specfem::element::medium_tag::elastic,
   *     specfem::element::property_tag::isotropic>(42);
   *
   * // Access material properties
   * auto density = elastic_material.get_density();
   * auto vp = elastic_material.get_p_velocity();
   * auto vs = elastic_material.get_s_velocity();
   *
   * // Use in wave equation computations
   * compute_elastic_forces(elastic_material, element_coords);
   * @endcode
   */
  template <specfem::element::medium_tag MediumTag,
            specfem::element::property_tag PropertyTag,
            specfem::element::attenuation_tag AttenuationTag>
  specfem::medium_container::material<dimension_tag, MediumTag, PropertyTag,
                                      AttenuationTag>
  get_material(const int index) const {
#ifndef NDEBUG
    if (index < 0 || index >= this->nspec) {
      KOKKOS_ABORT_WITH_LOCATION("Element index out of range in get_material");
    }
#endif
    const auto &material_specification = this->material_index_mapping[index];

#ifndef NDEBUG
    if (material_specification.type != MediumTag ||
        material_specification.property != PropertyTag ||
        material_specification.attenuation != AttenuationTag) {
      KOKKOS_ABORT_WITH_LOCATION("Material type mismatch in get_material");
    }
#endif

    using Key = specfem::tags::Tags<dimension_tag, MediumTag, PropertyTag,
                                    AttenuationTag>;
    return material_containers.template get<Key>()
        .element_materials[material_specification.index];
  }

  template <specfem::element::medium_tag MediumTag,
            specfem::element::property_tag PropertyTag,
            specfem::element::attenuation_tag AttenuationTag>
  const specfem::point::properties<
      specfem::tags::Tags<dimension_tag, MediumTag, PropertyTag, false> >
  get_properties(const int index) const {
    const auto material =
        this->get_material<MediumTag, PropertyTag, AttenuationTag>(index);
    return material.get_properties();
  }

  template <specfem::element::medium_tag MediumTag,
            specfem::element::property_tag PropertyTag>
  specfem::point::properties<
      specfem::tags::Tags<dimension_tag, MediumTag, PropertyTag, false> > const
  get_properties(const int index) const {
    using Result = specfem::point::properties<
        specfem::tags::Tags<dimension_tag, MediumTag, PropertyTag, false> >;
    constexpr auto att_combos =
        specfem::tag_dispatch::dimension_set<dimension_tag>{} *
        specfem::tag_dispatch::medium_set<MediumTag>{} *
        specfem::tag_dispatch::property_set<PropertyTag>{} *
        ATTENUATION_SET(none, constant_isotropic);
    const specfem::element::attenuation_tag runtime_att =
        this->material_index_mapping[index].attenuation;
    std::optional<Result> result;
    specfem::tag_dispatch::for_each(att_combos, [&]<typename TagsType>() {
      if (TagsType::attenuation_tag == runtime_att)
        result =
            get_properties<MediumTag, PropertyTag, TagsType::attenuation_tag>(
                index);
    });
    if (!result)
      KOKKOS_ABORT_WITH_LOCATION(
          "Invalid attenuation tag for material combination");
    return *result;
  }

  /**
   * @brief Get reference to material container for specific medium and property
   * types
   *
   * Returns a reference to the internal container storing materials of the
   * specified type combination for direct access by material management
   * functions.
   *
   * @tparam MediumTag Medium type (acoustic, elastic)
   * @tparam PropertyTag Property type (isotropic, anisotropic)
   * @return Reference to the material container for specified types
   *
   * @code
   * // Get container for elastic isotropic materials
   * auto& elastic_container = materials.get_container<
   *     specfem::element::medium_tag::elastic,
   *     specfem::element::property_tag::isotropic>();
   *
   * // Access container properties
   * int num_elastic_materials = elastic_container.n_materials;
   * auto& material_vector = elastic_container.element_materials;
   *
   * // Direct manipulation (use with caution)
   * elastic_container.element_materials.reserve(expected_count);
   * @endcode
   */
  template <specfem::element::medium_tag MediumTag,
            specfem::element::property_tag PropertyTag,
            specfem::element::attenuation_tag AttenuationTag>
  specfem::mesh::materials<dimension_tag>::material<MediumTag, PropertyTag,
                                                    AttenuationTag> &
  get_container() {

    using Key = specfem::tags::Tags<dimension_tag, MediumTag, PropertyTag,
                                    AttenuationTag>;
    return material_containers.template get<Key>();
  }

  /**
   * @brief Add a new material to the database
   *
   * Adds a material to the appropriate container based on its type, updates
   * counts, and creates mapping to the original MESHFEM3D database index.
   *
   * @tparam MediumTag Medium type (acoustic, elastic)
   * @tparam PropertyTag Property type (isotropic, anisotropic)
   * @param new_material Material object to add
   * @param database_index Original MESHFEM3D database index
   * @return Local index of the added material within its container
   *
   * @code
   * // Add elastic isotropic material from MESHFEM3D database
   * specfem::medium_container::material<specfem::element::medium_tag::elastic,
   *                          specfem::element::property_tag::isotropic> mat;
   * const auto index = materials.add_material(mat);
   * @endcode
   */
  template <specfem::element::medium_tag MediumTag,
            specfem::element::property_tag PropertyTag,
            specfem::element::attenuation_tag AttenuationTag>
  int add_material(const specfem::medium_container::material<
                   dimension_tag, MediumTag, PropertyTag, AttenuationTag>
                       &new_material) {
    this->n_materials += 1;
    auto &material_container =
        this->get_container<MediumTag, PropertyTag, AttenuationTag>();
    material_container.element_materials.push_back(new_material);
    material_container.n_materials += 1;

    return material_container.n_materials - 1;
  }

  void apply_attenuation(const specfem::mesh::attenuation_config &config) {
    if (!config.enabled)
      return;
    using specfem::units::unit_symbols::Hz;
    const auto fc = specfem::utilities::logarithmic_center(
                        config.band.min.raw(), config.band.max.raw()) *
                    Hz;
    auto &container =
        get_container<specfem::element::medium_tag::elastic,
                      specfem::element::property_tag::isotropic,
                      specfem::element::attenuation_tag::constant_isotropic>();
    for (auto &material : container.element_materials) {
      material.compute_attenuation_properties(fc.raw(), config.f0.raw(),
                                              config.band, config.tau_sigma);
    }
  }

  /**
   * @brief Get the medium and property types for a given element index
   *
   * Returns a tuple containing the medium and property tags associated with
   * the material specification for the specified element index.
   *
   * @param index Element index to query
   * @return Tuple of (medium_tag, property_tag) for the element's material
   *
   * @code
   * // Get material type for element 42
   * auto [medium, property] = materials.get_material_type(42);
   *
   * // Use in conditional logic
   * if (medium == specfem::element::medium_tag::elastic &&
   *     property == specfem::element::property_tag::isotropic) {
   *     // Handle elastic isotropic case
   * }
   * @endcode
   */
  std::tuple<specfem::element::medium_tag, specfem::element::property_tag,
             specfem::element::attenuation_tag>
  get_material_type(const int index) const {
#ifndef NDEBUG
    if (index < 0 || index >= this->nspec) {
      KOKKOS_ABORT_WITH_LOCATION(
          "Element index out of range in get_material_type");
    }
#endif
    const auto &material_specification = this->material_index_mapping[index];
    return std::make_tuple(material_specification.type,
                           material_specification.property,
                           material_specification.attenuation);
  }

  /** @} */ // End Material Access Interface
}; // End materials<dim3> specialization
} // namespace specfem::mesh
