include: "../../../seispie.smk"


rule all:
    input:
        trace_list="<cwd>/traces/trace_list.txt",
        database="<cwd>/database.bin",
    localrule: True


rule export_traces:
    input:
        ry="<cwd>/provenance/seispie/output/ry_000000.npy",
        iry="<cwd>/provenance/seispie/output/iry_000000.npy",
        cry="<cwd>/provenance/seispie/output/cry_000000.npy",
        ux="<cwd>/provenance/seispie/output/ux_000000.npy",
        uz="<cwd>/provenance/seispie/output/uz_000000.npy",
    output:
        trace_list="<cwd>/traces_fd/trace_list.txt",
    localrule: True,
    run:
        import numpy as np
        cmps = {
            "ry": ("BXY", "semr"),
            "iry": ("BXY", "semir"),
            "cry": ("BXY", "semc"),
            "ux": ("BXX", "semd"),
            "uz": ("BXZ", "semd"),
        }

        trs = []

        for trace in ["ry", "ux", "uz", "iry", "cry"]:
            trace_ref = np.load(input[trace])
            for i in range(trace_ref.shape[0]):
                tr = np.zeros([1000, 2])
                tr[:, 0] = np.linspace(-0.12, 0.879,1000)
                tr[:, 1] = trace_ref[i, ::5]
                tr_name = f"AA.S000{i + 1}.S2.{cmps[trace][0]}.{cmps[trace][1]}"
                np.savetxt(f"traces_fd/{tr_name}", tr)
                trs.append(tr_name)

        with open(output.trace_list, "w") as f:
            for tr in trs:
                f.write(f"{tr}\n")
