changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - dependency
  categories:
    - title: 🚨 Breaking Changes
      labels:
        - breaking-change
    - title: 🚀 New Features
      labels:
        - enhancement
        - feature
    - title: 👨‍🔬 New physics 
      labels:
        - new physics
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: Refactor 
      labels:
        - refactor
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🔧 Maintenance
      labels:
        - maintenance
    - title: 🧾 New tests
      labels:
        - tests
    - title: Other Changes
      labels:
        - "*"
