#ifndef _SPECFEM_RUNTIME_CONFIGURATION_SOLVER_INTERFACE_HPP_
#define _SPECFEM_RUNTIME_CONFIGURATION_SOLVER_INTERFACE_HPP_

#include "solver.hpp"
#include "solver.tpp"

#endif // _SPECFEM_RUNTIME_CONFIGURATION_SOLVER_INTERFACE_HPP_
