number-of-sources: 1
sources:
  - force:
      x : 5.0
      z : 7.0
      source_surf: false
      angle : 0.0
      vx : 0.0
      vz : 0.0
      Ricker:
        factor: 1e2
        tshift: 0.0
        f0: 1e9
