number-of-sources: 1
sources:
  - force:
      x : 50000.0
      z : 80000.0
      source_surf: false
      angle : 0.0
      vx : 0.0
      vz : 0.0
      dGaussian:
        factor: 1e10
        tshift: 0.0
        f0: 2.0
