parameters:

  header:
    ## Header information is used for logging. It is good practice to give your simulations explicit names
    title: Heterogeneous acoustic-elastic medium with 1 acoustic-elastic interface # name for your simulation
    # A detailed description for your simulation
    description: |
      Material systems : Elastic domain (1), Acoustic domain (1)
      Interfaces : Acoustic-elastic interface (1)
      Sources : Force source (1)
      Boundary conditions : Neumann BCs on all edges

  simulation-setup:
    ## quadrature setup
    quadrature:
      alpha: 0.0
      beta: 0.0
      ngllx: 5
      ngllz: 5

    ## Solver setup
    solver:
      time-marching:
        type-of-simulation: forward
        time-scheme:
          type: Newmark
          dt: 0.85e-3
          nstep: 800

  receivers:
    stations: "/scratch/gpfs/rk9481/specfem2d_kokkos/examples/fluid_solid_interface/OUTPUT_FILES/STATIONS"
    angle: 0.0
    seismogram-type:
      - displacement
      - velocity
    nstep_between_samples: 1

  ## Runtime setup
  run-setup:
    number-of-processors: 1
    number-of-runs: 1

  ## databases
  databases:
    mesh-database: "/scratch/gpfs/rk9481/specfem2d_kokkos/examples/fluid-solid-interface/OUTPUT_FILES/database.bin"
    source-file: "/scratch/gpfs/rk9481/specfem2d_kokkos/examples/fluid-solid-interface/sources.yaml"

  seismogram:
    seismogram-format: ascii
    output-folder: "."
