pipeline{

    agent {
        node {
            label 'della_rk9481'
        }
    }

    stages{

        stage( ' Build ' ){
            steps {

                echo ' Getting git submodules '
                sh 'git submodule init'
                sh 'git submodule update'

                echo ' Loading required module '

                sh 'module load intel/2022.2.0'

                echo ' Building '

                sh 'cmake3 -S . -B build -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DCMAKE_BUILD_TYPE=Release'

                sh 'cmake3 --build build'

                echo ' Build completed '
            }
        }

        stage( ' Test ' ){

            steps {

                echo ' Running Unit Tests '

                sh 'cd build/tests/unit-tests && ctest'
            }
        }
    }
}
