pipeline{

    agent {
        node {
            label 'della_rk9481'
        }
    }

    stages{

        stage( ' Load git modules ' ){

            steps {

                echo ' Getting git submodules '
                sh 'git submodule init'
                sh 'git submodule update'
            }
        }

        stage ( ' Load required modules ' ){

            steps {
                echo ' Loading required module '

                sh 'module load intel/2022.2.0'
            }
        }

        stage ( ' Build ' ){
            environment {
                // Define C compiler
                CC = '/opt/intel/oneapi/compiler/2022.2.0/linux/bin/icx'
                // Using CXX compiler
                CXX = '/opt/intel/oneapi/compiler/2022.2.0/linux/bin/icpx'
            }

            steps {
                echo ' Building '

                sh 'cmake3 -S . -B build -DCMAKE_BUILD_TYPE=Release'

                sh 'cmake3 --build build'

                echo ' Build completed '
            }

        }

        stage( ' Test ' ){

            steps {

                echo ' Running Unit Tests '

                sh 'cd build/tests/unit-tests && ctest'
            }
        }
    }
}
