pipeline{

    agent none

    stages{

        stage( " Build main " ){
            steps {

                echo " Getting git submodules "
                git submodule init
                git submodule update

                echo " Loading required module "

                echo " Building "

                cmake3 -S . -B build -DCMAKE_BUILD_TYPE=Release

                cmake3 --build build

                echo " Build completed "
            }
        }

        stage( " Test Main " ){

            steps {

                echo " Running Unit Tests "

                cd build/tests/unit-tests

                ctest
            }
        }
    }
}
