source_file = "FORCESOLUTION"

include: "../../../specfem3d.smk"

networks = ["X", "Y", "Z", "XYZ"]
stations = ["S0000", "S0001", "S0002", "S0003"]
locations = ["S3"]
channels = ["MXX","MXY","MXZ"]
extensions = ["semd", "semv", "sema"]

traces = [
    f"traces/{network}.{station}.{location}.{channel}.{extension}"
    for network in networks
    for station in stations
    for location in locations
    for channel in channels
    for extension in extensions
]


rule all:
    input:
        traces=traces,
        trace_list="<cwd>/traces/trace_list.txt",
        database="<cwd>/database.bin",
    localrule: True


rule check_traces:
    input:
        trace_list="<cwd>/traces/trace_list.txt",
    output:
        traces=traces,
    localrule: True
