#pragma once

#include "specfem/tags.hpp"
#include <array>
#include <cstddef>
#include <string>
#include <type_traits>
#include <utility>

namespace specfem::tag_dispatch::impl {

/**
 * @brief Single index–value slot in a `TagValueTuple`.
 *
 * Stores one enum value `v` at compile-time position `I`.  Inheriting from
 * multiple `TagValueHolder` specialisations with distinct `I` values gives
 * unambiguous access via a `static_cast`.
 *
 * @tparam I   Slot index within the enclosing tuple.
 * @tparam T   Enum type stored at this slot.
 */
template <std::size_t I, typename T> struct TagValueHolder {
  T v{};
  constexpr TagValueHolder() = default;
  constexpr explicit TagValueHolder(T val) : v{ val } {}
};

/**
 * @brief Base implementation of a constexpr heterogeneous tuple of enum values.
 *
 * Inherits from `TagValueHolder<I, T>` for every (index, type) pair.  Uses
 * pack-expansion inheritance rather than `std::tuple` so that `operator=` and
 * construction remain `constexpr` in C++17.
 *
 * @tparam Is         Index pack generated by `std::make_index_sequence`.
 * @tparam TagTypes   Enum types stored in this tuple, one per slot.
 */
template <typename IndexSeq, typename... TagTypes> struct TagValueTupleBase;

template <std::size_t... Is, typename... TagTypes>
struct TagValueTupleBase<std::index_sequence<Is...>, TagTypes...>
    : TagValueHolder<Is, TagTypes>... {
  /** @brief Number of tag slots in this tuple. */
  static constexpr std::size_t arity = sizeof...(TagTypes);

  constexpr TagValueTupleBase() = default;
  /**
   * @brief Construct from individual enum values.
   * @param vs  One value per slot, in declaration order.
   */
  constexpr TagValueTupleBase(TagTypes... vs)
      : TagValueHolder<Is, TagTypes>{ vs }... {}

  /**
   * @brief Retrieve the value at compile-time index `I`.
   * @tparam I  Slot index (0-based).
   * @return    The stored enum value.
   */
  template <std::size_t I> constexpr auto get() const {
    using T = typename std::tuple_element<I, std::tuple<TagTypes...> >::type;
    return static_cast<const TagValueHolder<I, T> &>(*this).v;
  }

  /**
   * @brief Element-wise equality comparison.
   * @return `true` if all slots compare equal.
   */
  constexpr bool operator==(const TagValueTupleBase &o) const {
    return (... &&
            (static_cast<const TagValueHolder<Is, TagTypes> &>(*this).v ==
             static_cast<const TagValueHolder<Is, TagTypes> &>(o).v));
  }
};

/**
 * @brief Convenience alias: `TagValueTuple<T0, T1, ...>` expands
 *        `TagValueTupleBase` with a generated index sequence.
 *
 * @tparam TagTypes  Enum types, one per slot.
 */
template <typename... TagTypes>
using TagValueTuple =
    impl::TagValueTupleBase<std::make_index_sequence<sizeof...(TagTypes)>,
                            TagTypes...>;

/** @brief Tuple of (dimension, medium) used by `is_valid_medium_combo`. */
using MediumTagTuple = TagValueTuple<specfem::element::dimension_tag,
                                     specfem::element::medium_tag>;
/** @brief Tuple of (dimension, medium, property) used by
 * `is_valid_property_combo`. */
using PropertyComboTuple =
    TagValueTuple<specfem::element::dimension_tag, specfem::element::medium_tag,
                  specfem::element::property_tag>;
/** @brief Tuple of (dimension, medium, property, attenuation) used by
 * `is_valid_material_combo`. */
using MaterialTagTuple =
    TagValueTuple<specfem::element::dimension_tag, specfem::element::medium_tag,
                  specfem::element::property_tag,
                  specfem::element::attenuation_tag>;
/** @brief Tuple of (dimension, medium, property, boundary) used by
 * `is_valid_boundary_combo`. */
using BoundaryComboTuple =
    TagValueTuple<specfem::element::dimension_tag, specfem::element::medium_tag,
                  specfem::element::property_tag,
                  specfem::element::boundary_tag>;
/** @brief Tuple of (dimension, medium, property, attenuation, boundary) used by
 * `is_valid_full_combo`. */
using ElementTagTuple =
    TagValueTuple<specfem::element::dimension_tag, specfem::element::medium_tag,
                  specfem::element::property_tag,
                  specfem::element::attenuation_tag,
                  specfem::element::boundary_tag>;

/**
 * @brief Check whether a (dimension, medium) pair is a valid element type.
 *
 * dim2 supports: `elastic_psv`, `elastic_sh`, `elastic_psv_t`, `acoustic`,
 * `poroelastic`, `electromagnetic_te`.
 * dim3 supports: `elastic`, `acoustic`, `elastic_spin`.
 *
 * @param t  A `MediumTagTuple` holding (dimension, medium).
 * @return   `true` if the combination is physically valid.
 */
constexpr bool is_valid_medium_combo(MediumTagTuple t) {
  using D = specfem::element::dimension_tag;
  using M = specfem::element::medium_tag;
  auto d = t.get<0>();
  auto m = t.get<1>();
  if (d == D::dim2)
    return m == M::elastic_psv || m == M::elastic_sh || m == M::elastic_psv_t ||
           m == M::acoustic || m == M::poroelastic ||
           m == M::electromagnetic_te;
  if (d == D::dim3)
    return m == M::elastic || m == M::acoustic || m == M::elastic_spin;
  return false;
}

/**
 * @brief Check whether a (dimension, medium, property) triple is valid.
 *
 * Calls `is_valid_medium_combo` first, then applies medium-specific rules:
 * - `elastic_psv` / `elastic_sh` → `isotropic` or `anisotropic`.
 * - `elastic` (dim3), `acoustic`, `poroelastic`, `electromagnetic_te`
 *   → `isotropic`.
 * - Cosserat types (`elastic_psv_t`, `elastic_spin`) → `isotropic_cosserat`.
 *
 * @param t  A `PropertyComboTuple` holding (dimension, medium, property).
 * @return   `true` if the combination is physically valid.
 */
constexpr bool is_valid_property_combo(PropertyComboTuple t) {
  using M = specfem::element::medium_tag;
  using P = specfem::element::property_tag;
  auto d = t.get<0>();
  auto m = t.get<1>();
  auto p = t.get<2>();

  if (!is_valid_medium_combo({ d, m }))
    return false;

  switch (m) {
  case M::elastic_psv:
  case M::elastic_sh:
    return p == P::isotropic || p == P::anisotropic;
  case M::elastic: // dim3 elastic: isotropic only
    return p == P::isotropic;
  case M::elastic_psv_t:
  case M::elastic_spin: // Cosserat elastic: isotropic_cosserat
    return p == P::isotropic_cosserat;
  case M::acoustic:
  case M::poroelastic:
  case M::electromagnetic_te:
    return p == P::isotropic;
  case M::electromagnetic:
    return false; // not a material-level medium
  }
  return false;
}

/**
 * @brief Check whether a (dimension, medium, property, attenuation) quad is
 * valid.
 *
 * Cosserat (`elastic_psv_t`, `elastic_spin`) and `electromagnetic_te` media
 * require `attenuation_tag::none`; all other valid media accept both `none`
 * and `constant_isotropic`.
 *
 * @param t  A `MaterialTagTuple` holding (dimension, medium, property,
 * attenuation).
 * @return   `true` if the combination is physically valid.
 */
constexpr bool is_valid_material_combo(MaterialTagTuple t) {
  using M = specfem::element::medium_tag;
  using A = specfem::element::attenuation_tag;
  auto d = t.get<0>();
  auto m = t.get<1>();
  auto p = t.get<2>();
  auto a = t.get<3>();

  if (!is_valid_property_combo({ d, m, p }))
    return false;

  switch (m) {
  case M::elastic_psv: // dim2: isotropic and anisotropic
    return a == A::none || a == A::constant_isotropic;
  case M::elastic: // dim3: isotropic only
    return a == A::none || (a == A::constant_isotropic &&
                            p == specfem::element::property_tag::isotropic);
  case M::elastic_psv_t:
  case M::elastic_spin:       // Cosserat elastic: isotropic_cosserat × none
  case M::electromagnetic_te: // isotropic × none
    return a == A::none;
  default:
    return true; // none or constant_isotropic both valid for material storage
  }
}

/**
 * @brief Check whether a (dimension, medium, property, boundary) quad is valid.
 *
 * dim3 elements only support `boundary_tag::none`.  For dim2:
 * - `acoustic` accepts all boundary types.
 * - `electromagnetic_te` only accepts `none`.
 * - All other dim2 media accept `none` or `stacey`.
 *
 * @param t  A `BoundaryComboTuple` holding (dimension, medium, property,
 * boundary).
 * @return   `true` if the combination is physically valid.
 */
constexpr bool is_valid_boundary_combo(BoundaryComboTuple t) {
  using D = specfem::element::dimension_tag;
  using M = specfem::element::medium_tag;
  using B = specfem::element::boundary_tag;
  auto d = t.get<0>();
  auto m = t.get<1>();
  auto p = t.get<2>();
  auto b = t.get<3>();

  if (!is_valid_property_combo({ d, m, p }))
    return false;

  // dim3: boundary must be none
  if (d == D::dim3)
    return b == B::none;

  switch (m) {
  case M::acoustic:
    return true; // all boundary types allowed
  case M::electromagnetic_te:
    return b == B::none;
  default:
    return b == B::none || b == B::stacey;
  }
}

/**
 * @brief Check whether a full (dimension, medium, property, attenuation,
 * boundary) 5-tuple is a valid element configuration.
 *
 * Delegates to `is_valid_material_combo` and `is_valid_boundary_combo`;
 * both must return `true`.
 *
 * @param t  An `ElementTagTuple` holding all five tag values.
 * @return   `true` if the combination is physically valid.
 */
/**
 * @brief Check whether a (dimension, medium, property, attenuation) quad is
 * valid for element *computation* (stricter than material storage).
 *
 * constant_isotropic attenuation is only valid for mediums that have a
 * compute impl: elastic_psv (dim2) and elastic (dim3).
 */
constexpr bool is_valid_element_attenuation_combo(MaterialTagTuple t) {
  using M = specfem::element::medium_tag;
  using A = specfem::element::attenuation_tag;
  auto d = t.get<0>();
  auto m = t.get<1>();
  auto p = t.get<2>();
  auto a = t.get<3>();

  if (!is_valid_property_combo({ d, m, p }))
    return false;

  if (a == A::none)
    return true;

  // constant_isotropic only valid for mediums with an attenuation impl
  return (m == M::elastic_psv) || (m == M::elastic);
}

constexpr bool is_valid_full_combo(ElementTagTuple t) {
  auto d = t.get<0>();
  auto m = t.get<1>();
  auto p = t.get<2>();
  auto a = t.get<3>();
  auto b = t.get<4>();

  return is_valid_element_attenuation_combo({ d, m, p, a }) &&
         is_valid_boundary_combo({ d, m, p, b });
}

// ── Interface / coupling combinations ────────────────────────────────────────

using InterfaceSystemTuple =
    TagValueTuple<specfem::element::dimension_tag,
                  specfem::element_connections::type,
                  specfem::element_coupling::interface_tag>;

using EdgeTuple = TagValueTuple<
    specfem::element::dimension_tag, specfem::element_connections::type,
    specfem::element_coupling::interface_tag, specfem::element::boundary_tag>;

using EdgeFluxSchemeTuple = TagValueTuple<
    specfem::element::dimension_tag, specfem::element_connections::type,
    specfem::element_coupling::interface_tag, specfem::element::boundary_tag,
    specfem::element_coupling::flux_scheme_tag>;

/// Valid interface systems: weakly_conforming, elastic↔acoustic, dim2 or dim3.
constexpr bool is_valid_interface_system(InterfaceSystemTuple t) {
  using C = specfem::element_connections::type;
  using I = specfem::element_coupling::interface_tag;
  auto c = t.get<1>();
  auto i = t.get<2>();
  if (c != C::weakly_conforming)
    return false;
  return i == I::elastic_acoustic || i == I::acoustic_elastic;
}

/// Valid edge combinations (dim + connection + interface + boundary).
constexpr bool is_valid_edge(EdgeTuple t) {
  using D = specfem::element::dimension_tag;
  using C = specfem::element_connections::type;
  using I = specfem::element_coupling::interface_tag;
  using B = specfem::element::boundary_tag;
  auto d = t.get<0>();
  auto c = t.get<1>();
  auto i = t.get<2>();
  auto b = t.get<3>();

  if (c != C::weakly_conforming && c != C::nonconforming)
    return false;
  if (i != I::elastic_acoustic && i != I::acoustic_elastic)
    return false;

  // dim3: only weakly_conforming + none
  if (d == D::dim3)
    return c == C::weakly_conforming && b == B::none;

  // dim2: boundary rules depend on interface direction
  if (i == I::elastic_acoustic)
    return b == B::none || b == B::stacey;
  else // acoustic_elastic
    return b == B::none || b == B::stacey || b == B::acoustic_free_surface ||
           b == B::composite_stacey_dirichlet;
}

/// Valid edge + flux scheme combinations.
constexpr bool is_valid_edge_and_flux_scheme(EdgeFluxSchemeTuple t) {
  using D = specfem::element::dimension_tag;
  using F = specfem::element_coupling::flux_scheme_tag;
  auto d = t.get<0>();
  auto c = t.get<1>();
  auto i = t.get<2>();
  auto b = t.get<3>();
  auto f = t.get<4>();
  if (f == F::natural)
    return is_valid_edge({ d, c, i, b });
  if (f == F::symmetric_interior_penalty)
    return d == D::dim2 && is_valid_edge({ d, c, i, b });
  return false;
}

} // namespace specfem::tag_dispatch::impl
