#pragma once

#include "specfem/element_coupling.hpp"
#include "specfem/enums.hpp"
#include "specfem/mesh_entity.hpp"
#include <boost/graph/adjacency_list.hpp>
#include <memory>

namespace specfem::mesh {

template <specfem::element::dimension_tag DimensionTag> struct adjacency_graph;

/**
 * @brief 3D adjacency graph for MESHFEM3D spectral element connectivity
 *
 * This template specialization provides a graph-based representation of element
 * connectivity in 3D spectral element meshes generated by MESHFEM3D. The class
 * uses the Boost Graph Library to efficiently manage and query adjacency
 * relationships between spectral elements, including connection types and
 * geometric orientations.
 *
 * The adjacency graph encodes:
 * - **Element neighbors**: Which elements share faces, edges, or corners
 * - **Connection types**: Conforming vs. non-conforming interfaces
 * - **Geometric orientation**: Face/edge alignment between adjacent elements
 *
 * This graph structure is essential for:
 * - Flux calculations across element interfaces
 * - Discontinuous Galerkin coupling
 * - Boundary condition enforcement
 *
 * @tparam specfem::element::dimension_tag::dim3 Template specialization for 3D
 * meshes
 *
 * @see specfem::mesh::adjacency (CSR-based adjacency for solver)
 * @see specfem::element_connections::type
 * @see specfem::mesh_entity::dim3::type
 *
 * @code
 * // Example: Building adjacency graph from MESHFEM3D data
 * specfem::mesh::adjacency_graph<specfem::element::dimension_tag::dim3>
 *     adj_graph(nspec);
 *
 * // Add element connections with properties
 * auto& graph = adj_graph.graph();
 * boost::add_edge(elem1_id, elem2_id,
 *     EdgeProperties(specfem::element_connections::type::strongly_conforming,
 *                   specfem::mesh_entity::dim3::type::right), graph);
 *
 * // Query adjacency for spectral element computations
 * for (auto [edge_iter, edge_end] = boost::edges(graph);
 *      edge_iter != edge_end; ++edge_iter) {
 *     auto edge_props = graph[*edge_iter];
 *     // Process interface based on connection type and orientation
 * }
 * @endcode
 *
 * @note This class is primarily used during mesh preprocessing and setup.
 *       Runtime computations typically use the more efficient CSR format
 *       in specfem::mesh::adjacency.
 */
template <> struct adjacency_graph<specfem::element::dimension_tag::dim3> {
public:
  /**
   * @brief Edge properties for element interface characterization
   *
   * Stores the geometric and connectivity properties of interfaces between
   * adjacent spectral elements. Each edge in the adjacency graph represents
   * a shared interface (face, edge, or corner) between two elements, with
   * associated metadata describing the connection characteristics.
   *
   * @code
   * // Example: Creating edge properties for a conforming face interface
   * EdgeProperties face_props(
   *     specfem::element_connections::type::strongly_conforming,
   *     specfem::mesh_entity::dim3::type::right
   * );
   *
   * // Add to graph edge
   * boost::add_edge(elem1, elem2, face_props, graph);
   * @endcode
   */
  struct EdgeProperties {
    /**
     * @brief Type of connection between adjacent elements
     *
     * Specifies the conformity and coupling characteristics of the interface:
     * - **strongly_conforming**: Nodes match exactly (continuous coupling)
     * - **weakly_conforming**: Nodes match but allows discontinuous coupling
     * - **nonconforming**: No matching nodes, geometric adjacency only
     *
     * @see specfem::element_connections::type
     */
    specfem::element_connections::type connection;

    /**
     * @brief Geometric orientation of the shared interface
     *
     * Identifies which face, edge, or corner of the hexahedral element
     * participates in the adjacency relationship. This information is
     * crucial for:
     * - Flux computation across interfaces
     * - Proper geometric transformation setup
     * - Boundary condition application
     *
     * @see specfem::mesh_entity::dim3::type
     */
    specfem::mesh_entity::dim3::type orientation;

    /**
     * @brief Default constructor
     *
     * Creates edge properties with uninitialized values. This constructor
     * is used internally by Boost Graph Library during graph operations.
     */
    EdgeProperties() = default;

    /**
     * @brief Constructor with connection and orientation specification
     *
     * Creates edge properties for a specific interface between two elements,
     * encoding both the connection type and the geometric orientation.
     *
     * @param conn Type of connection (conforming/non-conforming)
     * @param orient Geometric orientation of the shared interface
     *
     * @code
     * // Create properties for a strongly conforming face interface
     * EdgeProperties props(
     *     specfem::element_connections::type::strongly_conforming,
     *     specfem::mesh_entity::dim3::type::right
     * );
     * @endcode
     */
    EdgeProperties(const specfem::element_connections::type conn,
                   const specfem::mesh_entity::dim3::type orient)
        : connection(conn), orientation(orient) {}
  };

  /**
   * @brief Properties of inter-partition adjacencies with anchor points
   *
   * Extends EdgeProperties with MPI-specific information for cross-partition
   * element adjacencies. Includes anchor point indices to provide deterministic
   * orientation information and eliminate rotational ambiguity on shared MPI
   * surfaces.
   *
   * The anchor points are element-absolute corner IDs (19-26 in 1-based Fortran
   * representation, matching specfem::mesh_entity::dim3::type convention) that
   * form a canonical reference frame for the shared interface. Unlike
   * interface-relative corner indices, element-absolute IDs provide global
   * position information within the hexahedron geometry:
   *   - 19: bottom_front_left      20: bottom_front_right
   *   - 21: bottom_back_left       22: bottom_back_right
   *   - 23: top_front_left         24: top_front_right
   *   - 25: top_back_left          26: top_back_right
   *
   * For a face interface (ncorners=4) or edge interface (ncorners=2), anchor
   * points identify which local and remote corners match by coordinate,
   * removing ambiguity when corner sets are equivalent but rotationally
   * distinct. This is essential for correct orientation-preserving assembly
   * and orientation constraint propagation across processor boundaries.
   *
   * @see EdgeProperties for connection type and orientation information
   * @see adjacency_graph.f90 (Fortran) for corner ID definitions
   */
  struct MPIEdgeProperties : public EdgeProperties {
    size_t neighbor_partition; ///< MPI rank of the neighboring partition for
                               ///< this edge
    specfem::mesh_entity::dim3::type neighbor_orientation; ///< Geometric
                                                           ///< orientation of
                                                           ///< the neighboring
                                                           ///< element's
                                                           ///< interface
    size_t neighbor_local_index; ///< Local index of the neighboring element in
                                 ///< the adjacent partition
    size_t local_index; ///< Local index of the element in the current partition
                        ///< associated with this edge
    specfem::mesh_entity::dim3::type local_anchor_point; ///< Element-absolute
                                                         ///< corner ID (range
                                                         ///< 19-26) of the
                                                         ///< anchor point on
                                                         ///< the local element.
    specfem::mesh_entity::dim3::type
        neighbor_anchor_point; ///< Element-absolute
                               ///< corner ID (range
                               ///< 19-26) of the
                               ///< anchor point on
                               ///< the neighboring
                               ///< element.

    MPIEdgeProperties() = default;

    /**
     * @brief Constructor with full MPI edge properties specification
     *
     * Creates an MPI edge property instance with all relevant information for
     * characterizing an inter-partition adjacency, including connection type,
     * geometric orientation, partition information, and anchor point IDs.
     *
     * @param conn Connection type (conforming/non-conforming)
     * @param orient Geometric orientation of the local interface
     * @param neighbor_rank MPI rank of the neighboring partition
     * @param neighbor_orientation Geometric orientation of the neighboring
     * interface
     * @param local_idx Local element index in the current partition
     * @param neighbor_local_idx Local element index in the neighboring
     * partition
     * @param local_anchor_idx Element-absolute corner ID (19-26) of the local
     * anchor point
     * @param neighbor_anchor_idx Element-absolute corner ID (19-26) of the
     * neighboring anchor point
     *
     * @code
     * // Example: Creating MPI edge properties for a cross-partition face
     * interface MPIEdgeProperties mpi_props(
     *     specfem::element_connections::type::strongly_conforming,
     *     specfem::mesh_entity::dim3::type::right,
     *     neighbor_rank, neighbor_orient, local_idx, neighbor_local_idx,
     *     local_anchor_idx, neighbor_anchor_idx);
     * @endcode
     */
    MPIEdgeProperties(
        const specfem::element_connections::type conn,
        const specfem::mesh_entity::dim3::type orient,
        const size_t neighbor_rank,
        const specfem::mesh_entity::dim3::type neighbor_orientation,
        const size_t local_idx, const size_t neighbor_local_idx,
        const specfem::mesh_entity::dim3::type local_anchor_idx,
        const specfem::mesh_entity::dim3::type neighbor_anchor_idx)
        : EdgeProperties(conn, orient), neighbor_partition(neighbor_rank),
          neighbor_orientation(neighbor_orientation),
          neighbor_local_index(neighbor_local_idx), local_index(local_idx),
          local_anchor_point(local_anchor_idx),
          neighbor_anchor_point(neighbor_anchor_idx) {}
  };

private:
  /**
   * @brief Boost Graph Library adjacency list type definition
   *
   * Uses directed adjacency list with:
   * - **vecS**: Vector-based vertex storage for O(1) access by element ID
   * - **vecS**: Vector-based edge storage for efficient iteration
   * - **directedS**: Directed edges to encode interface directionality
   * - **boost::no_property**: No vertex properties needed (element ID implicit)
   * - **EdgeProperties**: Rich edge metadata for interface characterization
   */
  using Graph =
      boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS,
                            boost::no_property, EdgeProperties>;

  /**
   * @brief Internal Boost Graph Library graph instance
   *
   * Stores the complete adjacency graph with vertices representing spectral
   * elements and edges representing interfaces with their properties.
   */
  std::shared_ptr<Graph> graph_;

  /**
   * @brief List of inter-partition edge properties with anchor constraints
   *
   * Stores MPI-specific adjacency information for all cross-partition element
   * connections. Each entry includes:
   * - Connection type and orientation from EdgeProperties
   * - Partition information (neighbor rank and local indices)
   * - Anchor point IDs: element-absolute corner indices (0-based range 18-25)
   *
   * Anchor points provide an additional constraint beyond coordinate matching.
   * They are element-absolute corner IDs (not interface-relative indices) that
   * identify specific hexahedron corners on local and remote elements,
   * disambiguating rotational variations among elements with equivalent corner
   * coordinate sets. This enables orientation-preserving assembly and
   * orientation constraint propagation across MPI boundaries.
   *
   * Anchor point mapping:
   *   - 18: bottom_front_left     19: bottom_front_right
   *   - 20: bottom_back_left      21: bottom_back_right
   *   - 22: top_front_left        23: top_front_right
   *   - 24: top_back_left         25: top_back_right
   *
   * For all adjacencies (faces and edges), anchor values are in range 18-25,
   * selected based on face/edge ID using mapping tables from
   * adjacency_graph.f90.
   *
   * @see MPIEdgeProperties
   * @see adjacency_graph.f90 (Fortran) for corner ID and mapping definitions
   */
  std::vector<MPIEdgeProperties> mpi_connections_;

public:
  int nspec; ///< Number of spectral elements in the mesh

  /**
   * @brief Default constructor
   *
   * Creates an empty adjacency graph with no vertices or edges.
   * Elements and connections must be added explicitly after construction.
   *
   * @code
   * specfem::mesh::adjacency_graph<specfem::element::dimension_tag::dim3>
   *     empty_graph;
   * // Graph must be populated with add_vertex/add_edge operations
   * @endcode
   */
  adjacency_graph() : nspec(0), graph_(std::make_shared<Graph>(0)) {}

  /**
   * @brief Constructor with pre-allocated vertex capacity
   *
   * Creates an adjacency graph with the specified number of vertices
   * (spectral elements) pre-allocated. This constructor is efficient when
   * the number of elements is known in advance from MESHFEM3D data.
   *
   * @param nspec Number of spectral elements in the mesh
   *
   * @code
   * // Create graph for mesh with 1000 spectral elements
   * specfem::mesh::adjacency_graph<specfem::element::dimension_tag::dim3>
   *     graph(1000);
   * // Vertices 0-999 are pre-allocated and ready for edge addition
   * @endcode
   */
  adjacency_graph(const int nspec)
      : nspec(nspec), graph_(std::make_shared<Graph>(nspec)) {}

  /**
   * @brief Mutable access to the underlying Boost Graph
   *
   * Provides direct access to the Boost Graph Library adjacency list for
   * advanced graph operations, including vertex/edge addition, modification,
   * and complex queries.
   *
   * @return Graph& Reference to the internal boost::adjacency_list
   *
   * @code
   * auto& graph = adj_graph.local_connections();
   *
   * // Add edge with properties
   * boost::add_edge(0, 1, EdgeProperties(
   *     specfem::element_connections::type::strongly_conforming,
   *     specfem::mesh_entity::dim3::type::right), graph);
   *
   * // Query neighbors
   * auto [adj_iter, adj_end] = boost::adjacent_vertices(0, graph);
   * @endcode
   */
  Graph &local_connections() { return *graph_; }

  /**
   * @brief Immutable access to the underlying Boost Graph
   *
   * Provides read-only access to the Boost Graph Library adjacency list for
   * queries and analysis operations without modification capabilities.
   *
   * @return const Graph& Const reference to the internal boost::adjacency_list
   *
   * @code
   * const auto& graph = adj_graph.local_connections();
   *
   * // Query graph properties
   * size_t num_elements = boost::num_vertices(graph);
   * size_t num_connections = boost::num_edges(graph);
   *
   * // Iterate over all edges
   * for (auto [edge_iter, edge_end] = boost::edges(graph);
   *      edge_iter != edge_end; ++edge_iter) {
   *     auto props = graph[*edge_iter];
   *     // Process edge properties
   * }
   * @endcode
   */
  const Graph &local_connections() const { return *graph_; }

  /**
   * @brief Mutable access to MPI inter-partition adjacencies with anchor
   * points
   *
   * Provides access to the list of cross-partition element adjacencies
   * including anchor point information. Used during mesh construction to
   * populate MPI adjacency data.
   *
   * @return std::vector<MPIEdgeProperties>& Reference to MPI connection
   *         properties list
   *
   * @code
   * auto &mpi_conns = adj_graph.mpi_connections();
   * for (const auto &mpi_edge : mpi_conns) {
   *     int neighbor_rank = mpi_edge.neighbor_partition;
   *     int neighbor_elem = mpi_edge.neighbor_local_index;
   *     int local_anchor = mpi_edge.local_anchor_point;    // 18-25
   *     int remote_anchor = mpi_edge.neighbor_anchor_point; // 18-25
   *     // Use anchor points to establish orientation constraint
   *     // Anchor IDs map to hexahedron corners via adjacency_graph.f90
   * }
   * @endcode
   */
  auto &mpi_connections() { return mpi_connections_; }

  /**
   * @brief Immutable access to MPI inter-partition adjacencies with anchor
   * points
   *
   * Provides read-only access to the list of cross-partition element
   * adjacencies including anchor point information. Used during simulation
   * to query MPI connectivity and orientation constraints.
   *
   * @return const std::vector<MPIEdgeProperties>& Const reference to MPI
   *         connection properties list
   *
   * @code
   * const auto &mpi_conns = adj_graph.mpi_connections();
   * size_t num_mpi_adjacencies = mpi_conns.size();
   * for (const auto &mpi_edge : mpi_conns) {
   *     // Query inter-partition adjacency data
   *     // Anchor points remove rotational ambiguity
   * }
   * @endcode
   *
   * @see MPIEdgeProperties
   */
  const auto &mpi_connections() const { return mpi_connections_; }

  /**
   * @brief Verify graph symmetry for undirected adjacency relationships
   *
   * Validates that the adjacency graph correctly represents undirected
   * element connections by ensuring that for every edge (u,v) there exists
   * a corresponding edge (v,u) with compatible properties. This is essential
   * for spectral element methods where interface coupling is symmetric.
   *
   * @throws std::runtime_error if asymmetric adjacency is detected
   *
   * @code
   * // Validate graph consistency after construction
   * try {
   *     adj_graph.assert_symmetry();
   *     std::cout << "Graph adjacency is symmetric" << std::endl;
   * } catch (const std::runtime_error& e) {
   *     std::cerr << "Adjacency error: " << e.what() << std::endl;
   * }
   * @endcode
   */
  void assert_symmetry() const;
};

} // namespace specfem::mesh
