#pragma once

#include "specfem/medium_container/impl/point_container.hpp"
#include <Kokkos_Core.hpp>

namespace specfem::medium_container::kernels {

/**
 * @defgroup specfem_point_kernels_acoustic_isotropic Acoustic Kernels
 * @{
 */

/**
 * @ingroup specfem_point_kernels_acoustic_isotropic
 * @brief Data container to hold misfit kernels of acoustic media at a
 * quadrature point
 *
 * Supports both 2D and 3D acoustic isotropic media. The kernel parameters
 * (density, bulk modulus, and derived velocity kernels) are dimension-
 * independent; the physical difference between 2D and 3D appears only in
 * the Fréchet derivative computation.
 *
 * @tparam DimensionTag Dimension of the problem (dim2 or dim3)
 * @tparam UseSIMD Boolean indicating whether to use SIMD intrinsics
 *
 * <b> Accessor functions generated by the </b> \c POINT_CONTAINER \c MACRO
 *
 * - Get @f$ K_{\rho} @f$
 *   @code KOKKOS_INLINE_FUNCTION const value_type rho() const @endcode
 * - Get @f$ K_{\kappa} @f$
 *   @code KOKKOS_INLINE_FUNCTION const value_type kappa() const @endcode
 * - Get @f$ K_{\rho_p} @f$
 *   @code KOKKOS_INLINE_FUNCTION const value_type rhop() const @endcode
 * - Get @f$ K_{\alpha} @f$
 *   @code KOKKOS_INLINE_FUNCTION const value_type alpha() const @endcode
 */
template <specfem::element::dimension_tag DimensionTag, bool UseSIMD>
struct point_container<DimensionTag, specfem::element::medium_tag::acoustic,
                       specfem::element::property_tag::isotropic, UseSIMD>
    /// @cond
    : public KernelsAccessor<DimensionTag,
                             specfem::element::medium_tag::acoustic,
                             specfem::element::property_tag::isotropic, UseSIMD>
/// @endcond
{

  using base_type =
      KernelsAccessor<DimensionTag, specfem::element::medium_tag::acoustic,
                      specfem::element::property_tag::isotropic, UseSIMD>;

  using value_type = typename base_type::value_type;
  using simd = typename base_type::simd;

  POINT_CONTAINER(rho, kappa, rhop, alpha)

  KOKKOS_FUNCTION
  point_container(const value_type rho, const value_type kappa)
      : point_container(rho, kappa, rho * kappa,
                        static_cast<type_real>(2.0) * kappa) {}
};

/** @} */ // end of group

} // namespace specfem::medium_container::kernels
