parameters:

    header:
        title: "Tromp-Tape-Liu (GJI 2005)"
        description: |
           Material systems : Elastic domain (1)
           Interfaces : None
           Sources : Force source (1)
           Boundary conditions : Free surface (1)
           Mesh : 2D Cartesian grid (1)
           Receiver : Displacement seismogram (1)
           Output : Wavefield at the last time step (1)
           Output : Seismograms in ASCII format (1)

    simulation-setup:
        quadrature:
            quadrature-type: GLL4

        solver:
            time-marching:
                time-scheme:
                   type: Newmark
                   dt: 0.02
                   nstep: 3000
                   t0: 8.0

        simulation-mode:
            combined:
                reader:
                    wavefield:
                        format: HDF5
                        directory: OUTPUT_FILES

                writer:
                    kernels:
                        format: ASCII
                        directory: OUTPUT_FILES/kernels

    receivers:
        stations-file: OUTPUT_FILES/STATIONS
        angle: 0.0
        seismogram-type:
            - displacement
        nstep_between_samples: 1

    run-setup:
        number-of-processors: 1
        number-of-runs: 1

    databases:
        mesh-database: OUTPUT_FILES/database.bin

    sources: adjoint_sources.yaml
