number-of-sources: 1
sources:
  - cosserat-force:
      x : 0.165
      z : 0.165
      source_surf: false
      angle : 0.0
      f : 0.0
      fc : 1.0
      Ricker:
        factor: 1e10
        tshift: 0.0
        f0: 1700.0
