#pragma once

#include "compute/assembly.hpp"
#include "compute/boundaries.hpp"
#include "compute/boundary_values.hpp"
#include "compute/coupled_interfaces.hpp"
#include "compute/fields.hpp"
#include "compute/interface_container.hpp"
#include "compute/jacobian_matrix.hpp"
#include "compute/kernels.hpp"
#include "compute/mesh.hpp"
#include "compute/properties.hpp"
#include "compute/receivers.hpp"
#include "compute/simulation_field.hpp"
#include "compute/source_medium.hpp"
#include "compute/sources.hpp"
