#pragma once

#include "enumerations/interface.hpp"
#include <Kokkos_Core.hpp>

namespace specfem::mesh {

template <specfem::dimension::type DimensionTag> struct control_nodes;

/**
 * @brief Container for control nodes used in 3D mesh generation with meshfem3D.
 *
 * The control_nodes class manages coordinate data for control nodes that define
 * the geometric structure of a 3D spectral element mesh generated by meshfem3D.
 *
 * @tparam Dimension Spatial dimension tag (must be dim3 for meshfem3D)
 *
 * @code
 * // Example: Reading control nodes from meshfem3D file
 * using control_nodes3D =
 * specfem::mesh::control_nodes<specfem::dimension::type::dim3>;
 *
 * // Read from binary file using IO routine
 * // The following code is only used internally by the IO module
 * auto control_nodes =
 * specfem::io::mesh::impl::fortran::dim3::meshfem3d::read_control_nodes(stream);
 *
 * // Access node coordinates
 * type_real x = control_nodes.coordinates(node_id, 0);  // x-coordinate
 * type_real y = control_nodes.coordinates(node_id, 1);  // y-coordinate
 * type_real z = control_nodes.coordinates(node_id, 2);  // z-coordinate
 * @endcode
 *
 * @see specfem::io::mesh::impl::fortran::dim3::meshfem3d::read_control_nodes
 * @see specfem::mesh::control_nodes (for general 2D control nodes)
 */
template <> struct control_nodes<specfem::dimension::type::dim3> {
public:
  /**
   * @brief Dimension tag identifying the spatial context.
   *
   * Static constant providing access to the template parameter for
   * compile-time dimension queries and type traits.
   */
  constexpr static auto dimension_tag = specfem::dimension::type::dim3;

private:
  /** @brief Compile-time dimension value extracted from template parameter */

  /**
   * @brief Kokkos view type for storing node coordinates.
   *
   * Two-dimensional view with layout [nnodes][3] storing xyz coordinates.
   * Uses LayoutLeft for column-major ordering and HostSpace for CPU memory.
   */
  using CoordinatesViewType =
      Kokkos::View<type_real *[3], Kokkos::LayoutLeft, Kokkos::HostSpace>;

  /**
   * @brief Kokkos view type for storing control node indices for elements.
   *
   * Two-dimensional view with layout [nspec][ngnod] storing control node
   * indices for each spectral element.
   */
  using ControlNodeIndexViewType =
      Kokkos::View<int **, Kokkos::LayoutLeft, Kokkos::HostSpace>;

public:
  /**
   * @brief Default constructor.
   *
   * Creates an uninitialized control_nodes object with no allocated storage.
   * The nnodes count and coordinates view remain in default state.
   */
  control_nodes() = default;

  /**
   * @brief Destructor.
   *
   * Automatically releases Kokkos view resources through RAII.
   */
  ~control_nodes() = default;

  /**
   * @brief Constructs control_nodes with specified node count for meshfem3D.
   *
   * Allocates storage for the given number of control nodes read from meshfem3D
   * binary files. Each node stores three coordinate components (x, y, z). This
   * constructor is typically called by IO routines when reading control node
   * data from meshfem3D output files.
   *
   * The coordinates are populated by reading from the binary file in the
   * format:
   * - node_index, x_coord, y_coord, z_coord (repeated for each node)
   *
   * @param nnodes_ Number of control nodes to allocate storage for (read from
   * file header)
   *
   * @code
   * // Typical usage in IO routine:
   * int nnodes;
   * specfem::io::read_fortran_line(stream, &nnodes);  // Read node count from
   * file control_nodes<specfem::dimension::type::dim3> control_nodes(nnodes);
   *
   * // Then populate coordinates from file
   * for (int inode = 0; inode < nnodes; ++inode) {
   *   int index;
   *   type_real x, y, z;
   *   specfem::io::read_fortran_line(stream, &index, &x, &y, &z);
   *   control_nodes.coordinates(inode, 0) = x;
   *   control_nodes.coordinates(inode, 1) = y;
   *   control_nodes.coordinates(inode, 2) = z;
   * }
   * @endcode
   */
  control_nodes(int ngnod_, int nnodes_)
      : ngnod(ngnod_), nnodes(nnodes_),
        coordinates("specfem::mesh::control_nodes", nnodes_) {}

  /**
   * @brief Number of control nodes stored.
   *
   * Represents the total count of control nodes defining the mesh geometry.
   * This value determines the first dimension of the coordinates view.
   */
  int nnodes;

  /**
   * @brief Number of control nodes per spectral element.
   *
   * Indicates how many control nodes define each spectral element in the mesh.
   * Typical values are 8 for hexahedral elements and 27 for trilinear elements.
   * This value determines the second dimension of the control_node_index view.
   */
  int ngnod;

  /**
   * @brief Number of spectral elements in the mesh.
   *
   * Represents the total count of spectral elements. This value determines the
   * first dimension of the control_node_index view.
   */
  int nspec;

  type_real xmin, xmax; ///< Minimum and maximum x-coordinates of control nodes
  type_real ymin, ymax; ///< Minimum and maximum y-coordinates of control nodes
  type_real zmin, zmax; ///< Minimum and maximum z-coordinates of control nodes

  /**
   * @brief 3D coordinates of all control nodes.
   *
   * Two-dimensional Kokkos view storing spatial coordinates with layout:
   * - coordinates(i, 0): x-coordinate of node i
   * - coordinates(i, 1): y-coordinate of node i
   * - coordinates(i, 2): z-coordinate of node i
   *
   * The view uses column-major ordering (LayoutLeft) for optimal memory
   * access patterns during mesh generation algorithms.
   *
   * @code
   * // Access coordinates
   * type_real x = nodes.coordinates(node_id, 0);
   * type_real y = nodes.coordinates(node_id, 1);
   * type_real z = nodes.coordinates(node_id, 2);
   *
   * // Set coordinates
   * nodes.coordinates(node_id, 0) = 1.5;  // x
   * nodes.coordinates(node_id, 1) = 2.0;  // y
   * nodes.coordinates(node_id, 2) = 0.5;  // z
   * @endcode
   */
  CoordinatesViewType coordinates;

  /**
   * @brief Control node indices for each spectral element.
   *
   * Two-dimensional Kokkos view storing control node indices for each spectral
   * element with layout:
   * - control_node_index(i, j): index of the j-th control node for element i
   *
   * The view uses column-major ordering (LayoutLeft) for optimal memory
   * access patterns during mesh generation algorithms.
   *
   * @code
   * // Access control node index for element and local node
   * int node_index = nodes.control_node_index(element_id, local_node_id);
   *
   * // Set control node index
   * nodes.control_node_index(element_id, local_node_id) = new_node_index;
   * @endcode
   */
  ControlNodeIndexViewType control_node_index;
};

} // namespace specfem::mesh
