#pragma once

#include "specfem/medium_container/impl/point_container.hpp"
#include <Kokkos_Core.hpp>

namespace specfem::medium_container::kernels {

/**
 * @defgroup specfem_point_kernels_elastic_isotropic 2D Elastic Isotropic
 * @{
 */
/**
 * @ingroup specfem_point_kernels_elastic_isotropic
 * @brief Data container to hold misfit kernels of 2D elastic isotropic media at
 * a quadrature point
 *
 * @tparam DimensionTag Dimension of the problem
 * @tparam MediumTag The medium tag
 * @tparam UseSIMD Boolean indicating whether to use SIMD intrinsics
 *
 * <b> Accessor functions generated by the </b> \c POINT_CONTAINER \c MACRO
 *
 * - Get @f$ K_{\rho} @f$
 *   @code KOKKOS_INLINE_FUNCTION const value_type rho() const @endcode
 * - Get @f$ K_{\mu} @f$
 *   @code KOKKOS_INLINE_FUNCTION const value_type mu() const @endcode
 * - Get @f$ K_{\kappa} @f$
 *   @code KOKKOS_INLINE_FUNCTION const value_type kappa() const @endcode
 * - Get @f$ K_{\rho^\prime} @f$
 *   @code KOKKOS_INLINE_FUNCTION const value_type rhop() const @endcode
 * - Get @f$ K_{\alpha} @f$
 *   @code KOKKOS_INLINE_FUNCTION const value_type alpha() const @endcode
 * - Get @f$ K_{\beta} @f$
 *   @code KOKKOS_INLINE_FUNCTION const value_type beta() const @endcode
 *
 */
template <specfem::element::dimension_tag DimensionTag,
          specfem::element::medium_tag MediumTag, bool UseSIMD>
struct point_container<
    DimensionTag, MediumTag, specfem::element::property_tag::isotropic, UseSIMD,
    std::enable_if_t<specfem::element::is_elastic<MediumTag>::value> >
    /// @cond
    : public KernelsAccessor<DimensionTag, MediumTag,
                             specfem::element::property_tag::isotropic, UseSIMD>
/// @endcond
{

  using base_type =
      KernelsAccessor<DimensionTag, MediumTag,
                      specfem::element::property_tag::isotropic, UseSIMD>;

  using value_type = typename base_type::value_type;
  using simd = typename base_type::simd;

  POINT_CONTAINER(rho, mu, kappa, rhop, alpha, beta)
};
/** @} */ // end of group

} // namespace specfem::medium_container::kernels
