include: "../../../specfem2d.smk"

stations = [f"S{i:04d}" for i in range(1, 21)]
seismograms = ["semd", "sema", "semv", "semp"]

traces = [
    f"traces/AA.{station}.S2.BXY.{seismo}"
    for station in stations
    for seismo in seismograms
]


rule all:
    input:
        traces=traces,
        trace_list="<cwd>/traces/trace_list.txt",
        database="<cwd>/database.bin",
    localrule: True


rule check_traces:
    input:
        trace_list="<cwd>/traces/trace_list.txt",
    output:
        traces=traces,
    localrule: True
