parameters:

  header:
    ## Header information is used for logging. It is good practice to give your simulations explicit names
    title: Isotropic Elastic simulation # name for your simulation
    # A detailed description for your simulation
    description: |
      Material systems : Elastic domain (1)
      Interfaces : None
      Sources : Force source (1)
      Boundary conditions : Neumann BCs on all edges

  simulation-setup:
    ## quadrature setup
    quadrature:
      quadrature-type: GLL4

    ## Solver setup
    solver:
      time-marching:
        time-scheme:
          type: Newmark
          dt: 4.25e-4
          nstep: 10000

    simulation-mode:
      forward:
        writer:
          seismogram:
            format: "ascii"
            directory: "/Users/rohit-kakodkar/Desktop/SPECFEMPP/examples/CUBIT/homogeneous_salt_dome/OUTPUT_FILES/results"

  receivers:
    stations: "/Users/rohit-kakodkar/Desktop/SPECFEMPP/examples/CUBIT/homogeneous_salt_dome/OUTPUT_FILES/STATIONS"
    angle: 0.0
    seismogram-type:
      - displacement
    nstep_between_samples: 1

  ## Runtime setup
  run-setup:
    number-of-processors: 1
    number-of-runs: 1

  ## databases
  databases:
    mesh-database: "/Users/rohit-kakodkar/Desktop/SPECFEMPP/examples/CUBIT/homogeneous_salt_dome/OUTPUT_FILES/database.bin"

  ## sources
  sources: "/Users/rohit-kakodkar/Desktop/SPECFEMPP/examples/CUBIT/homogeneous_salt_dome/source.yaml"
