import os

envvars:
    "SPECFEMPP_BINDIR",


nproc = 6
databases = [
    f"DATABASES_MPI/proc{rank:06d}_specfempp_database.bin"
    for rank in range(nproc)
]


rule all:
    input:
        databases,


rule mesh:
    input:
        par_file="DATA/Par_file",
        stations="DATA/STATIONS",
        source="DATA/CMTSOLUTION",
        mesher=os.path.join(os.environ["SPECFEMPP_BINDIR"], "xmeshfem3D_globe"),
    output:
        databases=databases,
        log="OUTPUT_FILES/output_mesher.txt",
    shell:
        """
        mkdir -p DATABASES_MPI OUTPUT_FILES
        mpirun -n {nproc} {input.mesher} > {output.log} 2>&1
        """


rule clean:
    shell:
        "rm -rf DATABASES_MPI OUTPUT_FILES .snakemake"
