include: "../../../specfem2d.smk"

stations = [f"S{i:04d}" for i in range(1, 16)]
components = ["BXX", "BXZ"]
seismograms = ["semd", "sema", "semv"]

traces = [
    f"traces/AA.{station}.S2.{component}.{seismo}"
    for station in stations
    for component in components
    for seismo in seismograms
]


rule all:
    input:
        traces=traces,
        trace_list="<cwd>/traces/trace_list.txt",
        database="<cwd>/database.bin",
    localrule: True


rule check_traces:
    input:
        trace_list="<cwd>/traces/trace_list.txt",
    output:
        traces=traces,
    localrule: True
