name: Build docs on PR
on: pull_request
jobs:
  build-and-preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: macos-12
    steps:
      - name: Requirements
        run: brew install doxygen
          && brew install sphinx-doc
          && pip3 install sphinx-rtd-theme
          && pip3 install breathe
          && pip3 install sphinx-sitemap
          && export PATH="/usr/local/opt/sphinx-doc/bin:$PATH
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build docs
        run: cd docs
          && make html
          && cd _build/html
          && touch .nojekyll
          && mkdir ../../../public
          && cp -r * ../../../public
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPECFEM_KOKKOS }}'
          projectId: specfem-kokkos
          expires: 7d
