#pragma once

#include "adjacency_graph/adjacency_graph.hpp"
#include "boundaries/boundaries.hpp"
#include "control_nodes/control_nodes.hpp"
#include "globe.hpp"
#include "materials/materials.hpp"
#include "specfem/enums.hpp"
#include "specfem/mesh/attenuation_config.hpp"
#include "tags/tags.hpp"

namespace specfem::mesh {

/**
 * @brief Shared 3D mesh data for Cartesian3D and Globe3D models.
 */
struct mesh_dim3_base {

  constexpr static auto dimension_tag =
      specfem::element::dimension_tag::dim3;       ///< Dimension tag
  constexpr static auto dimension = dimension_tag; ///< Dimension

  /**
   * @brief Number of spectral elements in the mesh
   *
   */
  int nspec;

  specfem::mesh_entity::element<dimension_tag> element_grid;

  /**
   * @brief Control node geometric data container
   *
   * Stores coordinate information and connectivity data for control nodes
   * that define the geometric structure of spectral elements. These nodes
   * are read from MESHFEM3D database files and represent the high-order
   * geometric mapping points used in spectral element discretization.
   *
   * @see specfem::mesh::control_nodes
   */
  specfem::mesh::control_nodes<dimension_tag> control_nodes;

  /**
   * @brief Material properties database
   *
   * Contains physical material properties (elastic, acoustic, poroelastic)
   * mapped to different regions of the mesh. Materials are organized by
   * medium type and property characteristics, enabling efficient material
   * property lookup during spectral element computations.
   *
   * @see specfem::mesh::materials
   */
  specfem::mesh::materials<dimension_tag> materials;

  /**
   * @brief Absorbing boundary condition specifications
   *
   * Stores information about mesh faces designated as absorbing boundaries
   * for implementing Stacey absorbing boundary conditions. These boundaries
   * prevent spurious wave reflections at domain edges by absorbing outgoing
   * seismic waves.
   *
   * @see specfem::mesh::boundaries
   */
  specfem::mesh::boundaries<dimension_tag> boundaries;

  /**
   * @brief Element adjacency graph
   *
   * Represents the connectivity relationships between spectral elements in
   * the mesh.
   *
   * @see specfem::mesh::adjacency_graph
   */
  specfem::mesh::adjacency_graph<dimension_tag> adjacency_graph;

  /** @brief Tags associated with each spectral element
   *
   * Stores the tags for each spectral element, which specify medium type,
   * property type, and boundary conditions.
   */
  specfem::mesh::tags<dimension_tag> tags;

  specfem::mesh::attenuation_config attenuation; ///< Attenuation configuration

  /**
   * @brief Setup coupled interfaces in the mesh
   *
   * Coupled interfaces are essential for multi-domain simulations where
   * different materials or physical models interact at shared boundaries.
   *
   * @note This function should be called after the mesh has been fully
   * initialized and all components (control_nodes, materials, boundaries)
   * have been populated from MESHFEM3D database files.
   */
  void setup_coupled_interfaces();

  mesh_dim3_base() = default;
  ~mesh_dim3_base() = default;
};

/**
 * @brief 3D mesh data container for MESHFEM3D-generated spectral element meshes
 *
 * This template specialization manages 3D mesh data structures generated by
 * MESHFEM3D. The mesh structure serves as the primary data interface between
 * MESHFEM3D database files and the SPECFEM++ computational engine.
 *
 * This design follows the SPECFEM3D workflow where MESHFEM3D generates binary
 * database files containing pre-computed mesh information, which are then read
 * by the main solver for efficient spectral element computations.
 *
 * @tparam specfem::element::dimension_tag::dim3 Template specialization for 3D
 * spatial dimension
 *
 * @see specfem::io::meshfem3d::read_3d_mesh
 * @see specfem::mesh::control_nodes
 * @see specfem::mesh::materials
 * @see specfem::mesh::boundaries
 *
 * @code
 * // Example: Reading a MESHFEM3D database
 * std::string param_file = "MESH/parameters.bin";
 * std::string database_file = "MESH/database.bin";
 *
 * // Read mesh from MESHFEM3D binary files
 * auto mesh = specfem::io::meshfem3d::read_3d_mesh(param_file, database_file);
 *
 * // Access mesh components
 * int num_nodes = mesh.control_nodes.ngnod;
 * int num_materials = mesh.materials.number_of_materials;
 * int num_absorbing_faces = mesh.absorbing_boundaries.nfaces;
 *
 * // Use in spectral element computation
 * // (mesh data is typically passed to solver initialization)
 * @endcode
 */
template <>
struct mesh<specfem::simulation::model::Cartesian3D> : public mesh_dim3_base {

  constexpr static auto model_tag =
      specfem::simulation::model::Cartesian3D; ///< Simulation model

  /// UTM projection zone (positive = Northern hemisphere, negative = Southern).
  /// Range: ±1–60. Only meaningful when suppress_utm_projection is false.
  int utm_projection_zone = 0;

  /// When true, mesh coordinates are Cartesian (no lat/lon to UTM conversion
  /// needed). When false, source/receiver lat/lon must be converted to UTM
  /// using utm_projection_zone.
  bool suppress_utm_projection = true;

  mesh() = default;
  ~mesh() = default;
};

/**
 * @brief 3-D globe raw mesh data container.
 *
 * Common 3-D topology, control-node, material-classification, boundary, and
 * adjacency fields are inherited from @c mesh_dim3_base. The @ref globe payload
 * stores the additional thin-database metadata required to evaluate final GLL
 * material properties through the globe model oracle during assembly setup.
 */
template <>
struct mesh<specfem::simulation::model::Globe3D> : public mesh_dim3_base {

  constexpr static auto model_tag =
      specfem::simulation::model::Globe3D; ///< Simulation model

  /** @brief Globe-specific reference geometry and model-oracle context. */
  specfem::mesh::globe_mesh_data globe;

  mesh() = default;
  ~mesh() = default;
};

} // namespace specfem::mesh
